defaults:
  warehouse_size: XSMALL
entries:
  - project_name: example_project
    env: dev
  - project_name: example_project
    env: prod
  - project_name: marketing
    env: dev
  - project_name: marketing
    env: prod